### PR TITLE
Update dependency github.com/maxbrunsfeld/counterfeiter/v6 to fix panic

### PR DESCRIPTION
**Pull request by awnumar**
Without this fix, the generation of mocks fails on my system with a panic because of a nil pointer dereference.

```bash
go get -u github.com/maxbrunsfeld/counterfeiter/v6
go mod tidy
```

### CODE REVIEW

**Comment by Benjamintf1** [comment]
Not sure why this is failing. Honestly, TIL we have checks.

**Comment by awnumar** [comment]
I'm not sure why this is failing either. The request to gstack returns a 400 Bad Request response 🤔 

Perhaps the [token](https://github.com/cloudfoundry-community/github-pr-resource/blob/main/.github/workflows/trigger-pr-resource-check.yml#L14C48-L14C74) has expired?

**Comment by Benjamintf1** [comment]
possibly @bgandon knows more about this?

**Comment by bgandon** [comment]
Sorry for the delay. The 400 error happens for such PRs because the tests are run in the context of your `awnumar:main` branch, that lives in your fork, and thus cannot provide the required token that is provided in this repo only.

**Comment by bgandon** [comment]
In the Concourse pipeline, the panic doesn't happen. ~~But it's pinned to Golang v1.21, and you've been building with Golang v1.22. I'll give a try to a bump and see how counterfeiter is upgraded.~~

**Edit:** bumping to v1.22 with same deps filed. But I could see that the `bump-deps` Concourse job didn't upgrade counterfeiter to v6.8.1 as it should have. Bumping it manually worked great.

**Comment by bgandon** [comment]
You change is now ported to the `main` branch and shall be released in the next version. Thanks!

**Pull request closed without merging**
