### PR TITLE
`trusted_teams`/`trusted_users` + various fixes

### PR DESCRIPTION
**Pull request by gcapizzi**
This adds a few fixes and features needed by the [Korifi](https://github.com/cloudfoundry/korifi) team:
* [this fix](https://github.com/ctreatma/github-pr-resource/commit/b2493fbdda9cbbc2dc3084f9222694ad387db8b5) solving the problem of skipped builds described in https://github.com/telia-oss/github-pr-resource/issues/26;
* a fix for unnecessary re-runs every time a PR is approved;
* a feature that adds the `trusted_teams` and `trusted_users` configuration params, allowing to specify teams and users that are always authorised to run tests.

### CODE REVIEW

**Comment by Benjamintf1** [comment]
`a fix for unnecessary re-runs every time a PR is approved;` 
Looks good to me
`[this fix](https://github.com/ctreatma/github-pr-resource/commit/b2493fbdda9cbbc2dc3084f9222694ad387db8b5) solving the problem of skipped builds described in https://github.com/telia-oss/github-pr-resource/issues/26;`
Interesting. My understanding is this was supposed to help with dealing with api limits, something we're currently actually seeing some difficulties with. Have you expirienced increased api rate limits with this setting?
`a feature that adds the trusted_teams and trusted_users configuration params, allowing to specify teams and users that are always authorised to run tests.`
same api limit question?

**Comment by Benjamintf1** [comment]
As a side note, I *Think* the version of this resource that's on dockerhub doesn't actually align with the version in code here D: 

I think there might be a commit on there that seems to be lost to history that's supposed to order the prs in order of approval date rather then commit date, but I can't find it. If I push over that, we might have to remake that part of the commit.

**Comment by b1tamara** [comment]
After experimenting with the changes provided by PR, here is our feedback:
- The docker-image mentioned in the README does not contain the new changes. The usage of the image failed with the error: failed to unmarshal request: json: unknown field "trusted_teams"
- After we build a new image on our own and tried it out, we noticed that there is an issue with ListTeamMembers call. We tried to get users for wg-app-runtime-platform-networking-extensions-approvers. If we used the source.access_token from a technical user, the list was empty. If I used my private github token, I got the correct members of the working group team. I am not sure if it related to permissions. (EDIT: The technical user has only "repo" in scope of the token. It seems to be not enough to get the member list.)
- README is outdated. Could you please update it and add the new `trusted_teams` and `trusted_users` configuration params to [Source Configuration](https://github.com/cloudfoundry-community/github-pr-resource#source-configuration).

**Comment by Benjamintf1** [comment]
@b1tamara TY for giving this a closer look!!

**Comment by Benjamintf1** [comment]
@b1tamara just to be clear, did you just use :latest, or push a fork? Cause if you wanted to test I'd push to a docker fork and use that to test.

**Comment by b1tamara** [comment]
@Benjamintf1 
I created a new image on the latest code base (eirini-forks/github-pr-resource) and pushed to a private registry to use. If you can push the image with the changes to `loggregatorbot/github-pr-resource` then we will move to this public image.

**Comment by danail-branekov** [comment]
Hi all,

Thanks for all the inputs and apologies for the delay addressing them.

> Have you expirienced increased api rate limits with this setting?

We have never hit rate limits but that does not mean that it can never happen. How about trying it like it is and if it causes trouble we can introduce an opt-in feature flag.

> The docker-image mentioned in the README does not contain the new changes

That docker image is in the loggregator dockerhub repository which we do not have access to. Also, updating the released image is up to the repository owners.

> It seems to be not enough to get the member list.

We have documented the additional token permissions in the README

> Could you please update it and add the new trusted_teams and trusted_users configuration params to Source Configuration

Done

**Comment by Benjamintf1** [comment]
Howdy, sorry I didn't notice this earlier. Ran the pr tests and it's looking like we have a failure. if you could fix that we can talk more about possibly merging this.

**Comment by danail-branekov** [comment]
Hey @Benjamintf1 

The linter failed because there was an unused function. The function has been deleted.

**Comment by Benjamintf1** [comment]
Image should be auto-created soon.

**Pull request merged**
